import PDFDocument from "pdfkit";
import nodemailer from "nodemailer";
import config from "../config/env.js";

// Initialize Nodemailer transporter
const emailTransporter = nodemailer.createTransport({
  service: config.email.service,
  auth: {
    user: config.email.user,
    pass: config.email.password,
  },
});

/**
 * Generate PDF report for detection results
 * Returns a Buffer containing the PDF data
 */
export const generateDetectionPdf = async (detectionData, fileName = "detection_report.pdf") => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: "A4",
      });

      const chunks = [];

      // Collect PDF data
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });

      // Title
      doc.fontSize(20).font("Helvetica-Bold").text("SAR Detection Report", { align: "center" });
      doc.moveDown(0.5);

      // Report Metadata
      doc.fontSize(11).font("Helvetica").fillColor("#666666");
      doc.text(`Generated: ${new Date().toLocaleString()}`);
      doc.text(`Report ID: ${detectionData.id || "N/A"}`);
      doc.moveDown(1);

      // Image Information
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#000000").text("Image Information");
      doc.fontSize(10).font("Helvetica").fillColor("#333333");
      doc.text(`File Name: ${detectionData.fileName || "Unknown"}`);
      doc.text(`Upload Time: ${detectionData.uploadTime || new Date().toLocaleString()}`);
      doc.moveDown(1);

      // Detection Results
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#000000").text("Detection Results");
      doc.moveDown(0.3);

      if (!detectionData.predictions || detectionData.predictions.length === 0) {
        doc.fontSize(10).font("Helvetica").fillColor("#999999");
        doc.text("No targets detected in this image.", { indent: 20 });
      } else {
        detectionData.predictions.forEach((detection, index) => {
          doc.fontSize(10).font("Helvetica-Bold").fillColor("#1a1a1a");
          doc.text(`Detection ${index + 1}:`, { indent: 20 });

          doc.fontSize(9).font("Helvetica").fillColor("#333333");
          doc.text(`Target Class: ${detection.class || "Unknown"}`, { indent: 40 });
          doc.text(`Confidence: ${(detection.confidence * 100).toFixed(2)}%`, { indent: 40 });
          doc.text(`Type: ${detection.type || "N/A"}`, { indent: 40 });
          doc.text(`Threat Level: ${detection.threat || "N/A"}`, { indent: 40 });
          doc.text(`Impact: ${detection.harm || "N/A"}`, { indent: 40 });

          if (detection.bbox) {
            doc.text(
              `Bounding Box: [${detection.bbox.map((v) => v.toFixed(2)).join(", ")}]`,
              { indent: 40 }
            );
          }

          doc.moveDown(0.2);
        });
      }

      doc.moveDown(1);

      // Summary
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#000000").text("Summary");
      doc.fontSize(10).font("Helvetica").fillColor("#333333");
      doc.text(
        `Total Detections: ${detectionData.predictions?.length || 0}`,
        { indent: 20 }
      );

      const avgConfidence =
        detectionData.predictions && detectionData.predictions.length > 0
          ? (
              detectionData.predictions.reduce((sum, d) => sum + d.confidence, 0) /
              detectionData.predictions.length
            ).toFixed(3)
          : "N/A";

      doc.text(`Average Confidence: ${avgConfidence}`, { indent: 20 });
      doc.moveDown(1);

      // Footer
      doc.fontSize(8).font("Helvetica").fillColor("#999999");
      doc.text("This report is automatically generated by SAR Detection System", {
        align: "center",
      });
      doc.text("Confidential - For Authorized Personnel Only", { align: "center" });

      doc.end();
    } catch (error) {
      console.error("❌ PDF Generation Error:", error.message);
      reject(error);
    }
  });
};

/**
 * Send detection report via email
 */
export const sendDetectionReportEmail = async (recipientEmail, detectionData, pdfBuffer) => {
  try {
    console.log("📧 Sending detection report to:", recipientEmail);

    const fileName = `detection_report_${Date.now()}.pdf`;

    const mailOptions = {
      from: config.email.from,
      to: recipientEmail,
      subject: `SAR Detection Report - ${detectionData.predictions?.length || 0} targets detected`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 8px 8px 0 0; color: white;">
            <h2 style="margin: 0; font-size: 24px;">SAR Detection Report</h2>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">New detection results available</p>
          </div>
          
          <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 8px 8px;">
            <h3 style="color: #333; margin-top: 0;">Detection Summary</h3>
            
            <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
              <tr style="background: #e9ecef;">
                <td style="padding: 10px; border: 1px solid #dee2e6; font-weight: bold;">Total Detections</td>
                <td style="padding: 10px; border: 1px solid #dee2e6;">${
                  detectionData.predictions?.length || 0
                }</td>
              </tr>
              <tr>
                <td style="padding: 10px; border: 1px solid #dee2e6; font-weight: bold;">Report Generated</td>
                <td style="padding: 10px; border: 1px solid #dee2e6;">${new Date().toLocaleString()}</td>
              </tr>
              <tr style="background: #e9ecef;">
                <td style="padding: 10px; border: 1px solid #dee2e6; font-weight: bold;">File Name</td>
                <td style="padding: 10px; border: 1px solid #dee2e6;">${detectionData.fileName || "Unknown"}</td>
              </tr>
            </table>

            ${
              detectionData.predictions && detectionData.predictions.length > 0
                ? `
              <h4 style="color: #333; margin-top: 20px; margin-bottom: 10px;">Detected Targets</h4>
              <ul style="margin: 0; padding-left: 20px;">
                ${detectionData.predictions
                  .map(
                    (d) =>
                      `<li style="margin: 8px 0; color: #555;">
                      <strong>${d.class}</strong> - Confidence: ${(d.confidence * 100).toFixed(1)}%, 
                      Threat: ${d.threat || "N/A"}
                    </li>`
                  )
                  .join("")}
              </ul>
            `
                : `<p style="color: #999; font-style: italic;">No targets were detected in the uploaded image.</p>`
            }

            <p style="margin-top: 20px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #666; font-size: 12px;">
              The full detection report has been attached as a PDF file.
            </p>

            <p style="margin-top: 20px; color: #999; font-size: 11px;">
              <strong>Note:</strong> This is an automated report. Please review for accuracy before taking any action.
            </p>
          </div>
        </div>
      `,
      attachments: [
        {
          filename: fileName,
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    };

    await emailTransporter.sendMail(mailOptions);
    console.log("✅ Detection report sent via email");
    return { success: true, message: "Report sent successfully" };
  } catch (error) {
    console.error("❌ Email sending error:", error.message);
    return { success: false, error: error.message };
  }
};
